apiVersion: v1
kind: ConfigMap
metadata:
  name: megamart-configmap
data:  
  PORT: "5001"
  GOOGLE_CLIENT_ID: "554296135447-r1gvbhjmir3vpsojtbm8s4sv1omqpmnh.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  SECRET: "mhaflu"
  GOOGLE_LOGIN_CLINET_ID: "6271277622-qr316mllvigdh8tj0ca67csaphmc7t5a.apps.googleusercontent.com"
  FIREBASE_API_KEY: "AIzaSyDQJqvcBRyCGJqIe5rqR7pA4V6nuc-AV24"
  FIREBASE_AUTH_DOMAIN: "megamart-bb04d.firebaseapp.com"
  FIREBASE_PROJECT_ID: "megamart-bb04d"
  FIREBASE_STORAGE_BUCKET: "megamart-bb04d.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "626032194043"
  FIREBASE_APP_ID: "1:626032194043:web:7ed92f011c71cb0ef65b5e"
  FIREBASE_MEASUREMENT_ID: "G-6F416HPER1"
  MONGO_URL: "mongodb+srv://megamart043:lkfAUpjbizZ7oeNT@cluster0.obommw7.mongodb.net/?retryWrites=true&w=majority"
  GOOGLE_LOGIN_SECRET: "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"
  LOGIN_CLIENT_ID: "6271277622-ddil3s0uouqvrol0kdhobdifmerg2n7p.apps.googleusercontent.com"
  LOGIN_SECRET_ID: "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"
  USER_EMAIL: "mohamedaflah186@gmail.com"
  USER_SECRETPASS: "frih rrud anvu ldpa"
  ADMIN_COLLECTION: "Admin"
  CART_COLLECTION: "Cart"
  CATEGORY_COLLECTION: "Category"
  ORDERS_COLLECTION: "Orders"
  PRODUCTS_COLLECTION: "Products"
  USER_COLLECTION: "User"
  ADDRESS_COLLECTION: "Address"
  BRAND_COLLECTION: "brand"
  OTP_COLLECTION: "OTP"
  WALLET_COLLECTION: "Walet"
  WHISHLIST_COLLECTION: "Whishlist"
  COUPON_COLLECTION: "Coupon"
  RETURN_COLLECTION: "returns"
  REFERAL_COLLECTION: "referal"
  CATEGORY_OFFER: "cateogoryOffer"
  PRODUCT_OFFER: "ProductOffer"
  RAZORPAY_KEYID: "rzp_test_4DklPLkGmokBbK"
  RAZORPAY_KEY_SECRET: "agNynpaGXFl4sYyf6LuewLrn"